import type { Metadata } from "next"
import "../globals.css"
import { Roboto } from "next/font/google"
import Navbar from "../components/navbar/Navbar"

const roboto = Roboto({
	subsets: ["latin"],
	variable: "--font-roboto",
	weight: ["300", "400", "500", "700"],
})

export const metadata: Metadata = {
	title: "RC Rouen - Official Website",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" className={`${roboto.variable} font-sans`}>
			<body>
				<header>
					<Navbar />
				</header>
				<main className="pt-14 md:pt-24">{children}</main>
			</body>
		</html>
	)
}
