import type { Metadata } from "next"
import "@/app/styles/globals.css"
import { Roboto } from "next/font/google"

import Image from "next/image"
import heroForEquipe from "@/public/heroForEquipe.jpg"
import { getGlobalConfigImages } from "@/sanity/utils/blog/getConfig"

const roboto = Roboto({
	subsets: ["latin"],
	variable: "--font-roboto",
	weight: ["300", "400", "500", "700"],
})

export const metadata: Metadata = {
	title: "RC Rouen - Official Website",
	description: "Generated by create next app",
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const globalConfigImages = await getGlobalConfigImages()

	const heroImage = globalConfigImages.filter(
		(image) => image.slug === "hero-header-for-team-content-page"
	)
	return (
		<>
			<div className="w-full max-h-96 overflow-hidden bg-white ">
				<Image
					src={heroImage[0].image_url}
					alt={heroImage[0].image_alt}
					width={0}
					height={0}
					className="object-cover  aspect-video"
				/>
			</div>

			{children}
		</>
	)
}
